trigger:
- main

pool: 
  PoolAgentSelf

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Local-K8s-Cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '$(System.DefaultWorkingDirectory)/deployment.yml'
